### ISSUE TITLE
Knowledge Graph search: open URIs in preview / knowledge graph view

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-php-ui#38]
Link knowledge graph URIs (ids) to view preview / knowledge graph view

**Comment by Mandalka** [comment]
[Knowledge graph IDs / URIs are now clickable links in the view "preview"](https://github.com/opensemanticsearch/open-semantic-search/issues/81).

Switch this links from URI to our view preview when https://github.com/opensemanticsearch/solr-php-ui/issues/33 done, so new more powerful preview of the search can be used for document preview instead of old preview.php.

**Comment by Mandalka** [comment]
URIs of RDF knowledge graph are now linked to (pre)view / graph view of the linked entity, so we can not only find but additional browse linked data within the UI.
