### ISSUE TITLE
XSS in view.list.php

### ISSUE THREAD

**Issue by honoki** [opensemanticsearch/solr-php-ui#9]
There's an XSS vulnerability in at least one view, i.e. src/templates/view.list.php.

Patch: https://github.com/honoki/solr-php-ui/commit/611ed5e114d67f38b5572bb1ce186a0b94f222a6

**Comment by honoki** [comment]
Note that this is no perfect fix, as it seems to break the `<mark> `functionality when searching.

**Comment by Mandalka** [comment]
After implementation of named entity recognition by machine learning instead of trusted user content/annotations all outputed variables are converted to HTML.

Snippets are rendered to HTML by Solr.

If there should be some value from data left that is not handled by htmlspecialchars or htmlentities please reopen.
